version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ordos:server
    ports:
      - "51084:51084"
    volumes: 
      - ./Ordos:/app/Ordos
    networks:
      db_nw:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ORDOS_CONNECTION_STRING: Host=postgres;Port=5432;Username=postgres;Password=changeme;Database=postgres;
    depends_on: 
      - db
  db:
    image: postgres:10
    restart: always
    ports:
      - "51085:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
      db_nw:
        aliases:
          - postgres
    environment:
      POSTGRES_PASSWORD: changeme
networks:
  db_nw:
    driver: bridge

volumes:
  pgdata: